version: '3'
services: 
  db_container:
    build: ./SQL/
    command: --default-authentication-plugin=mysql_native_password
  web_container:
    build: ./WEB/
    depends_on: 
    - db_container
    ports:
    - '7000:80'