# L5E5.yml
apiVersion: apps/v1    
kind: Deployment       
metadata:
  name: wafl
spec:
  selector:
    matchLabels:       
      component: wafl
  replicas: 1
  template:
    metadata:
      labels:
        component: wafl
    spec:
      containers:
        - name: spekt8
          image: ahmadhamid/spekt8
          ports:
            - containerPort: 3000
